### ISSUE TITLE
recursion limit ?

### ISSUE THREAD

**Issue by nerzh** [tonlabs/ever-sdk#1019]
I use **sync** version of method tvm.run_get

<img width="618" alt="Снимок экрана 2023-08-02 в 02 55 12" src="https://github.com/tonlabs/ever-sdk/assets/10519803/4a4e9f5c-a308-4971-9c7a-4152dbf81ffe">

call this method like this

```ruby
out = run_get_method(addr: "-1:3333333333333333333333333333333333333333333333333333333333333333",
                     method_name: "participant_list_extended")
```

and I have this error: 

```bash
   Can't serialize result: recursion limit exceeded at line 1 column 29634
```

async version works fine

**Comment by elasticLove1** [comment]
Please, use tuple_list_as_array = true parameter, so that no recursion is used during serialization. This issue is caused by TVM linked lists implementation and when Serde library (json serializer) tries to serialize this linked list into json it fails by recursion structure limitations.  tuple_list_as_array param allows you to return data as an array.
